//! Dialog abstractions.

pub mod about_dialog;
pub mod admins_dialog;
pub mod bans_dialog;
pub mod base_dialog;
pub mod campaign_complete_dialog;
pub mod campaign_rules_dialog;
pub mod canvas_edit_dialog;
pub mod color_picker;
pub mod content_info_dialog;
pub mod custom_game_dialog;
pub mod custom_rules_dialog;
pub mod database_dialog;
pub mod discord_dialog;
pub mod editor_maps_dialog;
pub mod effects_dialog;
pub mod file_chooser;
pub mod full_text_dialog;
pub mod game_over_dialog;
pub mod host_dialog;
pub mod icon_select_dialog;
pub mod join_dialog;
pub mod keybind_dialog;
pub mod language_dialog;
pub mod launch_loadout_dialog;
pub mod load_dialog;
pub mod loadout_dialog;
pub mod map_list_dialog;
pub mod map_locales_dialog;
pub mod map_play_dialog;
pub mod mods_dialog;
pub mod palette_dialog;
pub mod paused_dialog;
pub mod planet_dialog;
pub mod research_dialog;
pub mod save_dialog;
pub mod schematics_dialog;
pub mod sector_select_dialog;
pub mod settings_menu_dialog;
pub mod trace_dialog;

pub use about_dialog::{
    about_link_rows, AboutContributorCell, AboutCreditsDialogModel, AboutCreditsDivider,
    AboutDialog, AboutDialogAction, AboutDialogButton, AboutDialogContext, AboutDialogModel,
    AboutLinkRow, ABOUT_BANNED_ITEMS_ON_IOS_OR_STEAM, ABOUT_CONTRIBUTORS_ENCODING,
    ABOUT_CONTRIBUTORS_FILE, ABOUT_CONTRIBUTORS_LABEL, ABOUT_CONTRIBUTOR_COLUMNS,
    ABOUT_CONTRIBUTOR_PAD, ABOUT_CONTRIBUTOR_PAD_LEFT, ABOUT_CONTRIBUTOR_PAD_RIGHT,
    ABOUT_CONTRIBUTOR_PREFIX, ABOUT_CREDITS_ALIGNMENT, ABOUT_CREDITS_BUTTON_SIZE,
    ABOUT_CREDITS_BUTTON_TEXT, ABOUT_CREDITS_DIVIDER_COLOR, ABOUT_CREDITS_DIVIDER_HEIGHT,
    ABOUT_CREDITS_DIVIDER_PAD, ABOUT_CREDITS_TEXT, ABOUT_CREDITS_TITLE, ABOUT_DIALOG_TITLE,
    ABOUT_LINK_BUTTON_ICON, ABOUT_LINK_BUTTON_STYLE, ABOUT_LINK_FAIL_ERROR,
    ABOUT_LINK_ICON_PAD_LEFT, ABOUT_LINK_LANDSCAPE_HEIGHT, ABOUT_LINK_LANDSCAPE_WIDTH,
    ABOUT_LINK_PAD_TOP, ABOUT_LINK_PANEL_MARGIN, ABOUT_LINK_PANEL_STYLE,
    ABOUT_LINK_PORTRAIT_HEIGHT, ABOUT_LINK_PORTRAIT_WIDTH, ABOUT_LINK_STRIPE_DARK_HEIGHT,
    ABOUT_LINK_STRIPE_WIDTH, ABOUT_OPEN_WIKI_TRIGGER,
};
pub use admins_dialog::{
    AdminPlayerInfo, AdminsDialog, AdminsDialogModel, AdminsDialogRow, ADMINS_DIALOG_ROW_HEIGHT,
    ADMINS_DIALOG_ROW_MARGIN, ADMINS_DIALOG_ROW_WIDTH, ADMINS_DIALOG_TITLE,
};
pub use bans_dialog::{
    BannedPlayerInfo, BansDialog, BansDialogModel, BansDialogRow, BANS_DIALOG_ROW_HEIGHT,
    BANS_DIALOG_ROW_MARGIN, BANS_DIALOG_ROW_WIDTH, BANS_DIALOG_TITLE,
};
pub use base_dialog::{
    BaseDialog, DialogAlignment, DialogResizeContext, DialogRuntime, DialogShellLayout,
    DialogState, DialogStyle,
};
pub use campaign_complete_dialog::{
    format_time, CampaignCompleteDialog, CampaignCompleteDialogModel, CampaignCompletePlanet,
    CAMPAIGN_COMPLETE_FADE_DURATION, CAMPAIGN_COMPLETE_MENU_BUTTON_SIZE,
    CAMPAIGN_COMPLETE_TRANSLATE_DURATION,
};
pub use campaign_rules_dialog::{
    CampaignRulesCheckKind, CampaignRulesCheckRow, CampaignRulesDialog, CampaignRulesDialogAction,
    CampaignRulesDialogContext, CampaignRulesDialogModel, CampaignRulesDialogPlanet,
    CampaignRulesDialogRuntime, CampaignRulesDifficultyButton, CampaignRulesDifficultyTable,
    CAMPAIGN_RULES_DIALOG_TITLE, CAMPAIGN_RULES_DIFFICULTY_BUTTON_SIZE,
    CAMPAIGN_RULES_DIFFICULTY_BUTTON_STYLE, CAMPAIGN_RULES_DIFFICULTY_TABLE_BACKGROUND,
    CAMPAIGN_RULES_DIFFICULTY_TABLE_MARGIN, CAMPAIGN_RULES_INNER_PAD,
};
pub use canvas_edit_dialog::{
    CanvasDrawPlan, CanvasEditAction, CanvasEditDialog, CanvasEditSpec, CanvasGridLine,
    CanvasPointerButton, CANVAS_EDIT_REFRESH_TIME,
};
pub use color_picker::{
    ColorPicker, ColorPickerAction, ColorPickerButton, ColorPickerColor, ColorPickerHexFieldModel,
    ColorPickerModel, ColorPickerPreviewModel, ColorPickerSliderBackground, ColorPickerSliderKind,
    ColorPickerSliderModel, ColorPickerUpdate, COLOR_PICKER_ALPHA_BACKGROUND,
    COLOR_PICKER_ALPHA_LINE_BACKGROUND, COLOR_PICKER_HEX_FIELD_SIZE, COLOR_PICKER_HUE_MAX,
    COLOR_PICKER_HUE_MIN, COLOR_PICKER_HUE_STEP, COLOR_PICKER_HUE_TEXTURE_FILTER,
    COLOR_PICKER_HUE_TEXTURE_HEIGHT, COLOR_PICKER_HUE_TEXTURE_WIDTH, COLOR_PICKER_OK_ICON,
    COLOR_PICKER_OK_TEXT, COLOR_PICKER_PREVIEW_BACKGROUND, COLOR_PICKER_PREVIEW_PAD_BOTTOM,
    COLOR_PICKER_PREVIEW_SIZE, COLOR_PICKER_SLIDER_HEIGHT, COLOR_PICKER_SLIDER_PAD_BOTTOM,
    COLOR_PICKER_SLIDER_WIDTH, COLOR_PICKER_TITLE, COLOR_PICKER_UNIT_MAX, COLOR_PICKER_UNIT_MIN,
    COLOR_PICKER_UNIT_STEP,
};
pub use content_info_dialog::{
    default_content_class_simple_name, fields_uri, ContentInfoBodyBlock, ContentInfoButton,
    ContentInfoCategoryBlock, ContentInfoContent, ContentInfoCreditBlock,
    ContentInfoDescriptionBlock, ContentInfoDetailsBlock, ContentInfoDialog,
    ContentInfoDialogAction, ContentInfoDialogContext, ContentInfoDialogModel,
    ContentInfoExtraBlock, ContentInfoHeader, ContentInfoKey, ContentInfoPatchedBanner,
    ContentInfoScrollPane, ContentInfoShowAction, ContentInfoStatBlock,
    CONTENT_INFO_CATEGORY_COLOR, CONTENT_INFO_CATEGORY_GENERAL, CONTENT_INFO_CATEGORY_PURPOSE,
    CONTENT_INFO_CONSOLE_NAME_PREFIX, CONTENT_INFO_CREDIT_COLOR, CONTENT_INFO_CREDIT_KEY,
    CONTENT_INFO_CREDIT_PAD_TOP, CONTENT_INFO_DESCRIPTION_COLOR_PREFIX,
    CONTENT_INFO_DESCRIPTION_PAD_LEFT_NO_STATS, CONTENT_INFO_DESCRIPTION_PAD_LEFT_WITH_STATS,
    CONTENT_INFO_DESCRIPTION_PAD_TOP_NO_STATS, CONTENT_INFO_DESCRIPTION_PAD_TOP_WITH_STATS,
    CONTENT_INFO_DESCRIPTION_WIDTH, CONTENT_INFO_DETAILS_COLOR_PREFIX, CONTENT_INFO_DETAILS_PAD,
    CONTENT_INFO_DETAILS_PAD_TOP, CONTENT_INFO_DETAILS_WIDTH, CONTENT_INFO_FIELDS_URI_PREFIX,
    CONTENT_INFO_HEADER_ACCENT_PREFIX, CONTENT_INFO_HEADER_NAME_PAD_LEFT,
    CONTENT_INFO_ICON_SCALING, CONTENT_INFO_ICON_SIZE, CONTENT_INFO_LOCK_ICON,
    CONTENT_INFO_PATCHED_COLOR, CONTENT_INFO_PATCHED_ICON, CONTENT_INFO_PATCHED_PAD,
    CONTENT_INFO_PATCHED_TEXT, CONTENT_INFO_PATCHED_TEXT_PAD_LEFT,
    CONTENT_INFO_RESHOW_FADE_DURATION, CONTENT_INFO_STAT_LABEL_PREFIX,
    CONTENT_INFO_STAT_LABEL_SUFFIX, CONTENT_INFO_STAT_PAD_LEFT, CONTENT_INFO_STAT_VALUE_SPACER,
    CONTENT_INFO_TABLE_MARGIN, CONTENT_INFO_TABLE_MARGIN_RIGHT, CONTENT_INFO_TITLE,
    CONTENT_INFO_UNLOCK_IN_CAMPAIGN, CONTENT_INFO_VIEW_FIELDS_ICON,
    CONTENT_INFO_VIEW_FIELDS_MARGIN, CONTENT_INFO_VIEW_FIELDS_PAD,
    CONTENT_INFO_VIEW_FIELDS_PAD_TOP, CONTENT_INFO_VIEW_FIELDS_SIZE,
    CONTENT_INFO_VIEW_FIELDS_STYLE, CONTENT_INFO_VIEW_FIELDS_TEXT,
};
pub use custom_game_dialog::{
    CustomGameDialog, CustomGameDialogAction, CustomGameDialogModel, CUSTOM_GAME_DIALOG_CAMPAIGN,
    CUSTOM_GAME_DIALOG_TITLE,
};
pub use custom_rules_dialog::*;
pub use database_dialog::{
    database_columns, database_content_unlocked, DatabaseCategorySection, DatabaseContent,
    DatabaseContentBadge, DatabaseContentCard, DatabaseDialog, DatabaseDialogAction,
    DatabaseDialogContext, DatabaseDialogModel, DatabaseDivider, DatabaseSearchModel, DatabaseTab,
    DatabaseTabButton, DatabaseTabIcon, DatabaseTagSection, DATABASE_ALL_MARGIN,
    DATABASE_ALL_MARGIN_RIGHT, DATABASE_ALL_MARGIN_TOP, DATABASE_ALL_TAB_ICON,
    DATABASE_ALL_TAB_NAME, DATABASE_ALL_TAB_TOOLTIP, DATABASE_BANNED_COLOR, DATABASE_BANNED_ICON,
    DATABASE_CATEGORY_COLOR, DATABASE_CATEGORY_DIVIDER_HEIGHT, DATABASE_CATEGORY_DIVIDER_PAD,
    DATABASE_CATEGORY_PREFIX, DATABASE_CONTENT_CELL_PAD, DATABASE_CONTENT_CELL_SIZE,
    DATABASE_CONTENT_COLUMN_WIDTH, DATABASE_CONTENT_COLUMN_WIDTH_PAD, DATABASE_COPIED_MESSAGE,
    DATABASE_DEFAULT_TAG, DATABASE_DIALOG_TITLE, DATABASE_LOCKED_COLOR, DATABASE_LOCK_ICON,
    DATABASE_MAX_COLUMNS, DATABASE_MIN_COLUMNS, DATABASE_NONE_FOUND, DATABASE_PATCHED_COLOR,
    DATABASE_PATCHED_ICON, DATABASE_PLANET_FALLBACK_ICON, DATABASE_SEARCH_ICON,
    DATABASE_SEARCH_MESSAGE, DATABASE_SEARCH_PAD_BOTTOM, DATABASE_SEARCH_PAD_RIGHT,
    DATABASE_TAB_COLUMNS, DATABASE_TAB_ICON_SIZE, DATABASE_TAB_SIZE, DATABASE_TAB_STYLE,
    DATABASE_TAG_COLOR, DATABASE_TAG_DIVIDER_HEIGHT, DATABASE_TAG_DIVIDER_PAD, DATABASE_TAG_PAD,
    DATABASE_TAG_PREFIX, DATABASE_TOOLTIP_BACKGROUND, DATABASE_UNLOCKED_DESKTOP_COLOR,
    DATABASE_UNLOCKED_MOBILE_COLOR,
};
pub use discord_dialog::{
    DiscordButton, DiscordButtonKind, DiscordCard, DiscordDialog, DiscordDialogAction,
    DiscordDialogModel, DISCORD_BACK_ICON, DISCORD_BACK_TEXT, DISCORD_BUTTON_SIZE,
    DISCORD_CARD_BACKGROUND, DISCORD_CARD_HEIGHT, DISCORD_CARD_PAD, DISCORD_CARD_WIDTH,
    DISCORD_COLOR_RGBA, DISCORD_COPIED_INFO, DISCORD_COPY_ICON, DISCORD_COPY_TEXT,
    DISCORD_DARK_COLOR_RGBA, DISCORD_DIALOG_MARGIN, DISCORD_DIALOG_TITLE, DISCORD_ICON,
    DISCORD_LINK_FAIL_ERROR, DISCORD_OPEN_ICON, DISCORD_OPEN_TEXT, DISCORD_STRIPE_DARK_HEIGHT,
    DISCORD_STRIPE_WIDTH, DISCORD_TEXT, DISCORD_TEXT_COLOR, DISCORD_TEXT_PAD_LEFT, DISCORD_URL,
};
pub use editor_maps_dialog::{
    editor_maps_buttons, next_unknown_import_name, EditorMapInfoButton, EditorMapInfoButtonAction,
    EditorMapInfoDialogModel, EditorMapInfoField, EditorMapInfoPanel, EditorMapInfoPreview,
    EditorMapsDialog, EditorMapsDialogAction, EditorMapsDialogModel, EDITOR_MAPS_BUTTON_SIZE,
    EDITOR_MAPS_CONFIRM_TITLE, EDITOR_MAPS_DIALOG_DISPLAY_TYPE, EDITOR_MAPS_DIALOG_TITLE,
    EDITOR_MAPS_EXISTS_ERROR, EDITOR_MAPS_IMAGE_ERROR, EDITOR_MAPS_IMPORT_EXISTS_KEY,
    EDITOR_MAPS_IMPORT_MAP_ICON, EDITOR_MAPS_IMPORT_MAP_TEXT, EDITOR_MAPS_MAP_DELETE_KEY,
    EDITOR_MAPS_MAP_EXTENSION, EDITOR_MAPS_NAME_ERROR, EDITOR_MAPS_NEW_MAP_ICON,
    EDITOR_MAPS_NEW_MAP_TEXT, EDITOR_MAPS_OVERWRITE_CONFIRM_KEY, EDITOR_MAPS_TEXT_INPUT_DEFAULT,
    EDITOR_MAPS_TEXT_INPUT_MESSAGE, EDITOR_MAPS_TEXT_INPUT_TITLE,
    EDITOR_MAP_INFO_ACTION_BUTTON_HEIGHT, EDITOR_MAP_INFO_ACTION_BUTTON_MARGIN_LEFT,
    EDITOR_MAP_INFO_AUTHOR_LABEL, EDITOR_MAP_INFO_DELETE_ICON, EDITOR_MAP_INFO_DELETE_TEXT,
    EDITOR_MAP_INFO_DESCRIPTION_LABEL, EDITOR_MAP_INFO_FALLBACK_AUTHOR,
    EDITOR_MAP_INFO_FIELD_LABEL_COLOR, EDITOR_MAP_INFO_FIELD_PAD_TOP,
    EDITOR_MAP_INFO_MAP_NOT_FOUND_ERROR, EDITOR_MAP_INFO_NAME_LABEL, EDITOR_MAP_INFO_OPEN_IN_ICON,
    EDITOR_MAP_INFO_OPEN_IN_TEXT, EDITOR_MAP_INFO_PANEL_MARGIN, EDITOR_MAP_INFO_PANEL_STYLE,
    EDITOR_MAP_INFO_PREVIEW_DESKTOP_SIZE, EDITOR_MAP_INFO_PREVIEW_PORTRAIT_SIZE,
    EDITOR_MAP_INFO_PREVIEW_SCALING, EDITOR_MAP_INFO_TITLE, EDITOR_MAP_INFO_VIEW_WORKSHOP_ICON,
    EDITOR_MAP_INFO_VIEW_WORKSHOP_TEXT,
};
pub use effects_dialog::{
    calculate_size, EffectPreviewDrawPlan, EffectPreviewState, EffectsBoundsBatch, EffectsDialog,
    EffectsDialogAction, EffectsDialogCell, EffectsDialogModel,
    EFFECTS_DIALOG_BACKGROUND_LIGHTNESS_HOVER, EFFECTS_DIALOG_BACKGROUND_LIGHTNESS_NORMAL,
    EFFECTS_DIALOG_BORDER_STROKE, EFFECTS_DIALOG_CELL_SIZE, EFFECTS_DIALOG_COLUMN_PAD,
    EFFECTS_DIALOG_TITLE,
};
pub use file_chooser::{
    escape_file_button_text, sorted_file_entries, FileChooser, FileChooserAction,
    FileChooserBottomButton, FileChooserBottomButtonKind, FileChooserEntry,
    FileChooserFileFieldModel, FileChooserFileListModel, FileChooserFileRow,
    FileChooserFilenameRow, FileChooserModel, FileChooserNavButton, FileChooserNavButtonKind,
    FileChooserNavigationCursor, FileChooserNavigationModel, FileHistory,
    FILE_CHOOSER_BOTTOM_BUTTON_HEIGHT, FILE_CHOOSER_CANCEL_TEXT, FILE_CHOOSER_CONT_MARGIN,
    FILE_CHOOSER_FIELD_HEIGHT, FILE_CHOOSER_FIELD_PAD_BOTTOM, FILE_CHOOSER_FIELD_PAD_LEFT,
    FILE_CHOOSER_FIELD_PAD_TOP, FILE_CHOOSER_FILEFIELD_ONLY_FONT_CHARS,
    FILE_CHOOSER_FILENAME_LABEL, FILE_CHOOSER_FILES_MARGIN_LEFT, FILE_CHOOSER_FILES_MARGIN_RIGHT,
    FILE_CHOOSER_FILE_BUTTON_HEIGHT, FILE_CHOOSER_FILE_BUTTON_PAD,
    FILE_CHOOSER_FILE_BUTTON_PAD_BOTTOM, FILE_CHOOSER_FILE_BUTTON_PAD_TOP,
    FILE_CHOOSER_FILE_BUTTON_STYLE, FILE_CHOOSER_FILE_ICON, FILE_CHOOSER_FILE_ICON_PAD_LEFT,
    FILE_CHOOSER_FILE_ICON_PAD_RIGHT, FILE_CHOOSER_FILL_PARENT, FILE_CHOOSER_FOLDER_ICON,
    FILE_CHOOSER_HOME_SETTING, FILE_CHOOSER_LABEL_ALIGNMENT, FILE_CHOOSER_LOAD_TEXT,
    FILE_CHOOSER_NAVIGATION_TOUCHABLE, FILE_CHOOSER_NAV_BACK_ICON, FILE_CHOOSER_NAV_BUTTON_HEIGHT,
    FILE_CHOOSER_NAV_BUTTON_PAD_TOP, FILE_CHOOSER_NAV_BUTTON_UNIFORM,
    FILE_CHOOSER_NAV_FORWARD_ICON, FILE_CHOOSER_NAV_HOME_ICON, FILE_CHOOSER_NAV_UP_ICON,
    FILE_CHOOSER_PANE_FADE_SCROLL_BARS, FILE_CHOOSER_PANE_OVER_SCROLL, FILE_CHOOSER_SAVE_TEXT,
    FILE_CHOOSER_UP_ROW_COLSPAN, FILE_CHOOSER_UP_ROW_ICON,
};
pub use full_text_dialog::FullTextDialog;
pub use game_over_dialog::{
    should_show_difficulty_guide, GameOverButton, GameOverButtonAction, GameOverContext,
    GameOverDialog, GameOverDialogAction, GameOverDialogModel, GameOverStatRow,
    GAME_OVER_BUTTON_SIZE, GAME_OVER_DIALOG_TITLE, GAME_OVER_MAX_SIZE, GAME_OVER_MENU_BUTTON_SIZE,
    GAME_OVER_MIN_WIDTH, GAME_OVER_STATS_PANE_PAD,
};
pub use host_dialog::{
    parse_port_or_default, valid_port, HostDialog, HostDialogAction, HostDialogContext,
    HostDialogModel, HOST_DIALOG_DEFAULT_PORT, HOST_DIALOG_DELAY_FRAMES,
    HOST_DIALOG_NAME_MAX_LENGTH, HOST_DIALOG_PORT_MAX_LENGTH, HOST_DIALOG_ROW_HEIGHT,
    HOST_DIALOG_SIDE_BUTTON_WIDTH, HOST_DIALOG_TITLE, HOST_DIALOG_WIDTH,
};
pub use icon_select_dialog::{
    IconSelectCell, IconSelectContentIcon, IconSelectDialog, IconSelectDialogModel,
    ICON_SELECT_BACK_BUTTON_SIZE, ICON_SELECT_BUTTON_SIZE, ICON_SELECT_COLUMN_WIDTH,
};
pub use join_dialog::{
    columns, group_view, host_matches_search, host_view, target_width, version_string, JoinDialog,
    JoinDialogAction, JoinDialogModel, JoinHostView, JoinKickReason, JoinRemoteServerRow,
    JoinRemoteStatus, JoinServer, JOIN_DIALOG_ADD_TITLE, JOIN_DIALOG_CONNECT_DELAY_FRAMES,
    JOIN_DIALOG_DEFAULT_PORT, JOIN_DIALOG_SERVER_CARD_PAD, JOIN_DIALOG_TARGET_WIDTH_MAX,
    JOIN_DIALOG_TITLE,
};
pub use keybind_dialog::{KeybindDialog, KeybindDialogRow};
pub use language_dialog::{
    LanguageDialog, LanguageDialogLocale, LanguageDialogRow, LANGUAGE_DIALOG_RESTART_MESSAGE_KEY,
    LANGUAGE_DIALOG_ROW_HEIGHT, LANGUAGE_DIALOG_ROW_WIDTH, LANGUAGE_DIALOG_TABLE_MARGIN_HORIZONTAL,
    LANGUAGE_DIALOG_TITLE_KEY,
};
pub use launch_loadout_dialog::{
    calculate_loadout, choose_schematic, LaunchCore, LaunchDestination, LaunchLoadoutButton,
    LaunchLoadoutCalculation, LaunchLoadoutContext, LaunchLoadoutDialog, LaunchLoadoutDialogAction,
    LaunchLoadoutDialogModel, LaunchLoadoutItemRow, LaunchLoadoutSchematic,
    LaunchLoadoutSchematicOption, LaunchSector, LAUNCH_LOADOUT_BACK_BUTTON_TEXT,
    LAUNCH_LOADOUT_BACK_ICON, LAUNCH_LOADOUT_BUTTON_SIZE, LAUNCH_LOADOUT_CONFIRM_ICON,
    LAUNCH_LOADOUT_CONFIRM_TEXT, LAUNCH_LOADOUT_DIALOG_TITLE, LAUNCH_LOADOUT_ITEM_ICON_SIZE,
    LAUNCH_LOADOUT_MAX_BUTTON_TEXT, LAUNCH_LOADOUT_MAX_ICON, LAUNCH_LOADOUT_MISSING_RESOURCES_TEXT,
    LAUNCH_LOADOUT_PORTRAIT_CONFIRM_WIDTH, LAUNCH_LOADOUT_RESOURCES_BUTTON_TEXT,
    LAUNCH_LOADOUT_RESOURCES_ICON, LAUNCH_LOADOUT_SCHEMATIC_BUTTON_PAD,
    LAUNCH_LOADOUT_SCHEMATIC_BUTTON_SIZE,
};
pub use load_dialog::{
    LoadDialog, LoadDialogAction, LoadDialogModeFilter, LoadDialogModel, LoadDialogSlotRow,
    LoadSaveSlot, LOAD_DIALOG_COLUMN_WIDTH, LOAD_DIALOG_META_WIDTH, LOAD_DIALOG_MODE_BUTTON_SIZE,
    LOAD_DIALOG_PREVIEW_SIZE, LOAD_DIALOG_SEARCH_MESSAGE, LOAD_DIALOG_SLOT_MARGIN,
    LOAD_DIALOG_SLOT_PAD, LOAD_DIALOG_SLOT_TITLE_WIDTH, LOAD_DIALOG_TITLE,
};
pub use loadout_dialog::{
    step, LoadoutDialog, LoadoutDialogAction, LoadoutDialogButton, LoadoutDialogContext,
    LoadoutDialogKey, LoadoutDialogModel, LoadoutItemButton, LoadoutItemRow,
    LOADOUT_AMOUNT_LABEL_WIDTH, LOADOUT_BACK_BUTTON_TEXT, LOADOUT_BACK_ICON, LOADOUT_BUTTON_SIZE,
    LOADOUT_DIALOG_TITLE, LOADOUT_EDIT_BUTTON_STYLE, LOADOUT_EDIT_ICON, LOADOUT_INVALID_KEY,
    LOADOUT_ITEMS_MARGIN, LOADOUT_ITEM_BACKGROUND, LOADOUT_ITEM_BUTTON_SIZE,
    LOADOUT_ITEM_BUTTON_STYLE, LOADOUT_ITEM_ICON_PAD, LOADOUT_ITEM_ICON_SIZE, LOADOUT_ITEM_MARGIN,
    LOADOUT_ITEM_MARGIN_RIGHT, LOADOUT_ITEM_OUTER_PAD, LOADOUT_MAX_BUTTON_TEXT, LOADOUT_MAX_ICON,
    LOADOUT_RESET_BUTTON_TEXT, LOADOUT_RESET_ICON, LOADOUT_TEXT_INPUT_MAX_LENGTH,
};
pub use map_list_dialog::{
    filtered_maps, map_columns, MapListBottomButton, MapListCard, MapListDialog,
    MapListDialogAction, MapListDialogContext, MapListDialogModel, MapListFilterAction,
    MapListFiltersModel, MapListMaps, MapListMapsModel, MapListModeFilterButton, MapListModeIcon,
    MapListPaneModel, MapListPlanet, MapListPlanetFilterButton, MapListPlanetFilterOption,
    MapListPlanetFiltersModel, MapListPriorityFilterButton, MapListPriorityKind,
    MapListSearchModel, MapListToggleFilterButton, MapListToggleKind, MAP_LIST_BACK_BUTTON_SIZE,
    MAP_LIST_BACK_BUTTON_TEXT, MAP_LIST_BACK_ICON, MAP_LIST_CARD_DIVIDER_COLOR,
    MAP_LIST_CARD_DIVIDER_PAD, MAP_LIST_CARD_MARGIN, MAP_LIST_CARD_MODE_ICON_PAD,
    MAP_LIST_CARD_MODE_ICON_SIZE, MAP_LIST_CARD_PAD, MAP_LIST_CARD_PREVIEW_SIZE,
    MAP_LIST_CARD_TITLE_WIDTH, MAP_LIST_CARD_TYPE_COLOR, MAP_LIST_CARD_TYPE_PAD_TOP,
    MAP_LIST_CARD_WIDTH, MAP_LIST_FILTER_BUTTON_SIZE, MAP_LIST_FILTER_BUTTON_STYLE,
    MAP_LIST_FILTER_DIALOG_TITLE, MAP_LIST_FILTER_ICON, MAP_LIST_FILTER_SECTION_MODE,
    MAP_LIST_FILTER_SECTION_PRIORITIES, MAP_LIST_FILTER_SECTION_SEARCH,
    MAP_LIST_FILTER_SECTION_TYPE, MAP_LIST_FILTER_STYLE, MAP_LIST_FILTER_TABLE_BACKGROUND,
    MAP_LIST_FILTER_TOOLTIP, MAP_LIST_FILTER_TYPE_BUTTON_SIZE, MAP_LIST_FILTER_TYPE_BUTTON_STYLE,
    MAP_LIST_NO_MAPS_TEXT, MAP_LIST_PANE_PAD_BOTTOM, MAP_LIST_PANE_PAD_LEFT,
    MAP_LIST_PLANET_ANY_NAME, MAP_LIST_PLANET_ANY_TEXT, MAP_LIST_PLANET_BUTTON_TOOLTIP,
    MAP_LIST_PLANET_FILTER_TITLE, MAP_LIST_PLANET_OPTION_SIZE, MAP_LIST_PLANET_OPTION_STYLE,
    MAP_LIST_PORTRAIT_BACK_BUTTON_SIZE, MAP_LIST_SEARCH_ICON, MAP_LIST_SEARCH_MAX_LENGTH,
    MAP_LIST_SEARCH_MESSAGE, MAP_LIST_SETTING_FILTER_PLANETS, MAP_LIST_SETTING_PRIORITIZE_CUSTOM,
    MAP_LIST_SETTING_PRIORITIZE_MODDED, MAP_LIST_SETTING_SEARCH_AUTHOR,
    MAP_LIST_SETTING_SEARCH_DESCRIPTION, MAP_LIST_SETTING_SEARCH_MOD_NAME,
    MAP_LIST_SETTING_SHOW_BUILTIN, MAP_LIST_SETTING_SHOW_CUSTOM, MAP_LIST_SETTING_SHOW_MODDED,
    MAP_LIST_TABLE_MARGIN_RIGHT,
};
pub use map_locales_dialog::{
    MapLocalesDialog, MapLocalesDialogLocaleAddRow, MapLocalesDialogLocaleEntry,
    MapLocalesDialogLocaleRow, MapLocalesDialogMainCard, MapLocalesDialogPropertyStatus,
    MapLocalesDialogPropertyViewCard, MAP_LOCALES_CARD_WIDTH, MAP_LOCALES_LOCALE_ADD_BUTTON_HEIGHT,
    MAP_LOCALES_LOCALE_ADD_BUTTON_WIDTH, MAP_LOCALES_LOCALE_DELETE_BUTTON_WIDTH,
    MAP_LOCALES_LOCALE_EDIT_BUTTON_WIDTH, MAP_LOCALES_LOCALE_ITEM_WIDTH,
    MAP_LOCALES_MAIN_PROPERTY_COLLAPSE_BUTTON_SIZE, MAP_LOCALES_MAIN_PROPERTY_EDIT_BUTTON_SIZE,
    MAP_LOCALES_MAIN_PROPERTY_FIELD_WIDTH, MAP_LOCALES_MAIN_PROPERTY_REMOVE_BUTTON_SIZE,
    MAP_LOCALES_MAIN_PROPERTY_VALUE_HEIGHT, MAP_LOCALES_MISSING_PLACEHOLDER,
    MAP_LOCALES_PROPERTY_VIEW_ADD_BUTTON_HEIGHT, MAP_LOCALES_PROPERTY_VIEW_ADD_BUTTON_WIDTH,
    MAP_LOCALES_PROPERTY_VIEW_VALUE_HEIGHT,
};
pub use map_play_dialog::{
    mode_buttons, preview_size, MapPlayButton, MapPlayDialog, MapPlayDialogAction,
    MapPlayDialogContext, MapPlayDialogModel, MapPlayHelpButton, MapPlayHelpDialogModel,
    MapPlayHelpEntry, MapPlayModeButton, MapPlayPreview, MAP_PLAY_CUSTOMIZE_BUTTON_SIZE,
    MAP_PLAY_CUSTOMIZE_BUTTON_TEXT, MAP_PLAY_CUSTOMIZE_ICON, MAP_PLAY_DIALOG_INITIAL_TITLE,
    MAP_PLAY_HELP_BUTTON_PAD_LEFT, MAP_PLAY_HELP_BUTTON_TEXT, MAP_PLAY_HELP_BUTTON_WIDTH,
    MAP_PLAY_HELP_ENTRY_WIDTH, MAP_PLAY_HELP_OK_BUTTON_PAD, MAP_PLAY_HELP_OK_BUTTON_SIZE,
    MAP_PLAY_HELP_OK_BUTTON_TEXT, MAP_PLAY_MODE_BUTTON_DESKTOP_HEIGHT,
    MAP_PLAY_MODE_BUTTON_MOBILE_HEIGHT, MAP_PLAY_MODE_BUTTON_STYLE, MAP_PLAY_MODE_BUTTON_WIDTH,
    MAP_PLAY_MODE_COLUMNS, MAP_PLAY_MODE_TABLE_BACKGROUND, MAP_PLAY_PLAY_BUTTON_SIZE,
    MAP_PLAY_PLAY_BUTTON_TEXT, MAP_PLAY_PLAY_ICON, MAP_PLAY_PREVIEW_BORDER_STROKE,
    MAP_PLAY_PREVIEW_DESKTOP_SIZE, MAP_PLAY_PREVIEW_MOBILE_LANDSCAPE_SIZE,
    MAP_PLAY_PREVIEW_SCALING,
};
pub use mods_dialog::*;
pub use palette_dialog::{
    PaletteColorButton, PaletteDialog, PaletteDialogAction, PaletteDialogModel,
    PALETTE_BUTTON_DRAWABLE, PALETTE_BUTTON_IMAGE_SIZE, PALETTE_BUTTON_SIZE, PALETTE_BUTTON_STYLE,
    PALETTE_COLUMNS, PALETTE_DIALOG_TITLE, PLAYER_COLORS,
};
pub use paused_dialog::{
    PauseContext, PausedDialog, PausedDialogAction, PausedDialogButton, PausedDialogButtonAction,
    PausedDialogModel, PAUSED_DESKTOP_BUTTON_HEIGHT, PAUSED_DESKTOP_BUTTON_PAD,
    PAUSED_DESKTOP_BUTTON_WIDTH, PAUSED_DIALOG_TITLE, PAUSED_MOBILE_BUTTON_SIZE,
};
pub use planet_dialog::{
    can_play_sector, can_select_sector, find_launcher, has_no_candidate, is_locked,
    selectable_planet, PlanetDialog, PlanetDialogAction, PlanetDialogContext, PlanetDialogMode,
    PlanetDialogPlanet, PlanetDialogPointerButton, PlanetDialogSector, PlanetSelectedPanelModel,
    PlanetSelectedPlayButton, PLANET_DIALOG_BACK_BUTTON_TEXT, PLANET_DIALOG_BACK_ICON,
    PLANET_DIALOG_BOTTOM_BUTTON_SIZE, PLANET_DIALOG_CAMPAIGN_RULES_ICON,
    PLANET_DIALOG_CAMPAIGN_RULES_SIZE, PLANET_DIALOG_CAMPAIGN_RULES_TEXT,
    PLANET_DIALOG_DEFAULT_PLANET, PLANET_DIALOG_INITIAL_TITLE, PLANET_DIALOG_PLANET_BUTTON_SIZE,
    PLANET_DIALOG_PLANET_BUTTON_STYLE, PLANET_DIALOG_SECTOR_SHOW_DURATION,
    PLANET_DIALOG_SELECTED_BACKGROUND, PLANET_DIALOG_SELECTED_PLAY_HEIGHT,
    PLANET_DIALOG_SELECTED_PLAY_MIN_WIDTH, PLANET_DIALOG_STYLE, PLANET_DIALOG_TECH_TREE_ICON,
    PLANET_DIALOG_TECH_TREE_TEXT,
};
pub use research_dialog::{
    can_spend, locked, selectable, ResearchBottomButtonModel, ResearchBounds,
    ResearchContentDetails, ResearchDialog, ResearchDialogAction, ResearchDialogContext,
    ResearchDialogKey, ResearchDialogModel, ResearchInfoBody, ResearchInfoButtonModel,
    ResearchInfoPanelModel, ResearchInlineDescription, ResearchItemDisplayModel,
    ResearchItemDisplayRow, ResearchItemInfo, ResearchItemSource, ResearchItemsModel,
    ResearchLinkModel, ResearchMobileResearchButton, ResearchNodeButtonModel,
    ResearchObjectiveModel, ResearchPlanetInventory, ResearchProgressModel,
    ResearchRequirementModel, ResearchRootPickerModel, ResearchRootPickerRow,
    ResearchSectorInventory, ResearchSectorItemCache, ResearchTitleButtonModel,
    ResearchTreeNodeModel, ResearchViewModel, RESEARCH_COMPLETED_TEXT, RESEARCH_COMPLETE_TEXT,
    RESEARCH_DATABASE_BUTTON_NAME, RESEARCH_DATABASE_BUTTON_SIZE, RESEARCH_DATABASE_ICON,
    RESEARCH_DATABASE_TEXT, RESEARCH_DEBUG_SHOW_REQUIREMENTS, RESEARCH_DIALOG_TITLE,
    RESEARCH_FALLBACK_PLANET, RESEARCH_INFO_BACKGROUND, RESEARCH_INFO_BUTTON_ICON,
    RESEARCH_INFO_BUTTON_STYLE, RESEARCH_INFO_BUTTON_WIDTH, RESEARCH_INFO_DESC_PAD,
    RESEARCH_INFO_MARGIN, RESEARCH_INITIAL_PAN_X, RESEARCH_INITIAL_PAN_Y, RESEARCH_INITIAL_SCALE,
    RESEARCH_INLINE_DESCRIPTION_COLOR, RESEARCH_INLINE_DESCRIPTION_LONG_MIN_WIDTH,
    RESEARCH_INLINE_DESCRIPTION_LONG_THRESHOLD, RESEARCH_INLINE_DESCRIPTION_MARGIN,
    RESEARCH_ITEM_DISPLAY_DEFAULT_MARGIN_TOP, RESEARCH_ITEM_DISPLAY_PORTRAIT_MARGIN_TOP,
    RESEARCH_LINE_COLOR_LOCKED, RESEARCH_LINE_COLOR_UNLOCKED, RESEARCH_LINE_STROKE,
    RESEARCH_LINE_Z_LOCKED, RESEARCH_LINE_Z_UNLOCKED, RESEARCH_LOCKED_COLOR, RESEARCH_LOCKED_TEXT,
    RESEARCH_MAX_SCALE, RESEARCH_MIN_SCALE, RESEARCH_MOBILE_RESEARCH_COLSPAN,
    RESEARCH_MOBILE_RESEARCH_DISABLED_DRAWABLE, RESEARCH_MOBILE_RESEARCH_HEIGHT,
    RESEARCH_MOBILE_RESEARCH_ICON, RESEARCH_MOBILE_RESEARCH_OVER_DRAWABLE,
    RESEARCH_MOBILE_RESEARCH_TEXT, RESEARCH_MOBILE_RESEARCH_UP_DRAWABLE,
    RESEARCH_NODE_IMAGE_COLOR_SELECTABLE_LOCKED, RESEARCH_NODE_IMAGE_COLOR_UNLOCKED,
    RESEARCH_NODE_IMAGE_COLOR_UNSELECTABLE, RESEARCH_NODE_IMAGE_LOCKED,
    RESEARCH_NODE_IMAGE_SCALING, RESEARCH_NODE_IMAGE_SIZE, RESEARCH_NODE_SIZE,
    RESEARCH_NODE_STYLE_UP_LOCKED, RESEARCH_NODE_STYLE_UP_UNAVAILABLE,
    RESEARCH_NODE_STYLE_UP_UNLOCKED, RESEARCH_OBJECTIVE_CANCEL_ICON,
    RESEARCH_OBJECTIVE_ICON_PAD_LEFT, RESEARCH_OBJECTIVE_OK_ICON, RESEARCH_OBJECTIVE_PREFIX,
    RESEARCH_PROGRESS_COLOR, RESEARCH_PROGRESS_KEY, RESEARCH_PROGRESS_MAX,
    RESEARCH_PROGRESS_SHINE_COLOR, RESEARCH_REQUIREMENT_ICON_PAD_RIGHT,
    RESEARCH_REQUIREMENT_ICON_SIZE, RESEARCH_REQUIREMENT_MISSING_COLOR,
    RESEARCH_REQUIREMENT_TEXT_COLOR, RESEARCH_SELECT_ROW_ICON_SIZE,
    RESEARCH_SELECT_ROW_MARGIN_LEFT, RESEARCH_SELECT_ROW_SIZE, RESEARCH_SELECT_ROW_STYLE,
    RESEARCH_SELECT_TITLE, RESEARCH_TITLE_COLOR, RESEARCH_TITLE_ICON_PAD_RIGHT,
    RESEARCH_TITLE_MIN_WIDTH, RESEARCH_TREE_SPACING,
};
pub use save_dialog::{
    SaveDialog, SaveDialogAction, SaveDialogModel, SAVE_DIALOG_LOADING_TEXT,
    SAVE_DIALOG_NEW_BUTTON, SAVE_DIALOG_NEW_MAX_LENGTH, SAVE_DIALOG_NEW_TEXT,
    SAVE_DIALOG_NEW_TITLE, SAVE_DIALOG_OVERWRITE_TEXT, SAVE_DIALOG_OVERWRITE_TITLE,
    SAVE_DIALOG_SAVE_DELAY_FRAMES, SAVE_DIALOG_TITLE,
};
pub use schematics_dialog::{
    schematic_columns, schematic_search_key, SchematicImageModel, SchematicsAllTagRow,
    SchematicsAllTagsDialogModel, SchematicsCardActionButton, SchematicsCardActionKind,
    SchematicsCardModel, SchematicsDescriptionModel, SchematicsDialog, SchematicsDialogAction,
    SchematicsDialogButton, SchematicsDialogContext, SchematicsDialogModel,
    SchematicsDialogSchematic, SchematicsEditDialogModel, SchematicsExportDialogModel,
    SchematicsIconButton, SchematicsImportDialogModel, SchematicsInfoDialogModel,
    SchematicsInfoLine, SchematicsNameOverlay, SchematicsPaneModel, SchematicsPowerEntry,
    SchematicsPowerModel, SchematicsRequirementRow, SchematicsSchematicTagChip,
    SchematicsSchematicTagsModel, SchematicsSearchModel, SchematicsTagBarModel, SchematicsTagChip,
    SchematicsTopButton, SCHEMATICS_ADD_ICON, SCHEMATICS_ADD_SMALL_ICON, SCHEMATICS_ADD_TAG_TITLE,
    SCHEMATICS_BACK_ICON, SCHEMATICS_BACK_TEXT, SCHEMATICS_BASE64_PREFIX,
    SCHEMATICS_BROWSE_WORKSHOP_TEXT, SCHEMATICS_CANCEL_ICON, SCHEMATICS_CANCEL_SMALL_ICON,
    SCHEMATICS_CANCEL_TEXT, SCHEMATICS_CARD_BUTTON_SIZE, SCHEMATICS_CARD_BUTTON_STYLE,
    SCHEMATICS_CARD_COLUMN_WIDTH, SCHEMATICS_CARD_NAME_BACKGROUND, SCHEMATICS_CARD_NAME_COLOR,
    SCHEMATICS_CARD_NAME_MAX_WIDTH, SCHEMATICS_CARD_NAME_PAD, SCHEMATICS_CARD_NAME_STYLE,
    SCHEMATICS_CARD_PAD, SCHEMATICS_CARD_PREVIEW_SIZE, SCHEMATICS_CARD_STYLE, SCHEMATICS_CARD_UP,
    SCHEMATICS_CONFIRM_TITLE, SCHEMATICS_COPIED_TEXT, SCHEMATICS_COPY_ICON,
    SCHEMATICS_COPY_IMPORT_TEXT, SCHEMATICS_COPY_TEXT, SCHEMATICS_DELETE_CONFIRM,
};
pub use sector_select_dialog::{
    matches_sector, normalized_search, SectorSelectDialog, SectorSelectDialogAction,
    SectorSelectDialogModel, SectorSelectRow, SECTOR_SELECT_DIALOG_TITLE, SECTOR_SELECT_ROW_HEIGHT,
    SECTOR_SELECT_ROW_ICON_SIZE, SECTOR_SELECT_ROW_MARGIN, SECTOR_SELECT_ROW_PAD,
    SECTOR_SELECT_ROW_STYLE, SECTOR_SELECT_ROW_WIDTH, SECTOR_SELECT_SEARCH_ICON,
    SECTOR_SELECT_SEARCH_WIDTH,
};
pub use settings_menu_dialog::*;
pub use trace_dialog::{
    TraceCopyRow, TraceDialog, TraceDialogModel, TraceInfo, TRACE_COPY_BUTTON_SIZE,
    TRACE_DIALOG_TITLE,
};
