//! Incremental Rust mirror of upstream `mindustry.entities.comp`.

pub mod block_unit;
pub mod building_tether;
pub mod child;
pub mod damage;
pub mod decal;
pub mod draw;
pub mod effect_state;
pub mod elevation_move;
pub mod entity;
pub mod fire;
pub mod health;
pub mod hitbox;
pub mod items;
pub mod launch_core;
pub mod owner;
pub mod physics;
pub mod pos;
pub mod pos_team_def;
pub mod power_graph_updater;
pub mod rot;
pub mod shield;
pub mod shielder;
pub mod sync;
pub mod team;
pub mod timed;
pub mod timed_kill;
pub mod timer;
pub mod underwater_move;
pub mod unit_tether;
pub mod vel;
pub mod water_crawl;
pub mod weapons;
pub mod world_label;

pub use block_unit::{BlockUnitBuilding, BlockUnitComp};
pub use building_tether::{BuildingTetherAction, BuildingTetherComp, BuildingTetherRef};
pub use child::{ChildComp, ChildParent};
pub use damage::DamageComp;
pub use decal::{DecalColor, DecalComp, DecalDrawPlan, DecalRegion};
pub use draw::DrawComp;
pub use effect_state::{EffectRenderInput, EffectStateComp};
pub use elevation_move::{ElevationMoveComp, SolidPred};
pub use entity::{EntityComp, EntityIoState, EntityLocality};
pub use fire::{FireComp, FireTile, FireUpdateContext, FireUpdatePlan};
pub use health::HealthComp;
pub use hitbox::{HitboxComp, HitboxRect};
pub use items::{ItemStackSlot, ItemsComp};
pub use launch_core::{LaunchCoreBlock, LaunchCoreComp, LaunchCoreDrawPlan, LaunchCoreSmoke};
pub use owner::OwnerComp;
pub use physics::{PhysicRef, PhysicsComp};
pub use pos::PosComp;
pub use pos_team_def::PosTeamDef;
pub use power_graph_updater::{PowerGraphUpdate, PowerGraphUpdaterComp};
pub use rot::RotComp;
pub use shield::{apply_armor, ShieldComp};
pub use shielder::{DamageState, ShielderComp, TeamState};
pub use sync::{SyncComp, SyncHooks};
pub use team::{TeamComp, TeamRulesView};
pub use timed::TimedComp;
pub use timed_kill::TimedKillComp;
pub use timer::{Interval, TimerComp};
pub use underwater_move::{UnderwaterDrawPlan, UnderwaterMoveComp};
pub use unit_tether::{UnitTetherAction, UnitTetherComp, UnitTetherRef};
pub use vel::VelComp;
pub use water_crawl::{WaterCrawlComp, WaterCrawlSolidPred};
pub use weapons::WeaponsComp;
pub use world_label::{WorldLabelAlign, WorldLabelComp, WorldLabelDrawPlan};
