//! Incremental Rust mirror of upstream `mindustry.entities.comp`.

pub mod child;
pub mod damage;
pub mod draw;
pub mod elevation_move;
pub mod entity;
pub mod health;
pub mod hitbox;
pub mod items;
pub mod owner;
pub mod pos;
pub mod pos_team_def;
pub mod power_graph_updater;
pub mod rot;
pub mod shield;
pub mod shielder;
pub mod sync;
pub mod team;
pub mod timed;
pub mod timed_kill;
pub mod timer;
pub mod vel;

pub use child::{ChildComp, ChildParent};
pub use damage::DamageComp;
pub use draw::DrawComp;
pub use elevation_move::{ElevationMoveComp, SolidPred};
pub use entity::{EntityComp, EntityIoState, EntityLocality};
pub use health::HealthComp;
pub use hitbox::{HitboxComp, HitboxRect};
pub use items::{ItemStackSlot, ItemsComp};
pub use owner::OwnerComp;
pub use pos::PosComp;
pub use pos_team_def::PosTeamDef;
pub use power_graph_updater::{PowerGraphUpdate, PowerGraphUpdaterComp};
pub use rot::RotComp;
pub use shield::{apply_armor, ShieldComp};
pub use shielder::{DamageState, ShielderComp, TeamState};
pub use sync::{SyncComp, SyncHooks};
pub use team::{TeamComp, TeamRulesView};
pub use timed::TimedComp;
pub use timed_kill::TimedKillComp;
pub use timer::{Interval, TimerComp};
pub use vel::VelComp;
