#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BlockFlag {
    Core,
    Storage,
    Generator,
    Turret,
    Factory,
    Repair,
    Battery,
    Reactor,
    Extinguisher,
    Drill,
    Shield,
    LaunchPad,
    UnitCargoUnloadPoint,
    UnitAssembler,
    HasFogRadius,
    SteamVent,
    BlockRepair,
    Synced,
}

impl BlockFlag {
    pub const ALL: [BlockFlag; 18] = [
        BlockFlag::Core,
        BlockFlag::Storage,
        BlockFlag::Generator,
        BlockFlag::Turret,
        BlockFlag::Factory,
        BlockFlag::Repair,
        BlockFlag::Battery,
        BlockFlag::Reactor,
        BlockFlag::Extinguisher,
        BlockFlag::Drill,
        BlockFlag::Shield,
        BlockFlag::LaunchPad,
        BlockFlag::UnitCargoUnloadPoint,
        BlockFlag::UnitAssembler,
        BlockFlag::HasFogRadius,
        BlockFlag::SteamVent,
        BlockFlag::BlockRepair,
        BlockFlag::Synced,
    ];
    pub const ALL_LOGIC: [BlockFlag; 10] = [
        BlockFlag::Core,
        BlockFlag::Storage,
        BlockFlag::Generator,
        BlockFlag::Turret,
        BlockFlag::Factory,
        BlockFlag::Repair,
        BlockFlag::Battery,
        BlockFlag::Reactor,
        BlockFlag::Drill,
        BlockFlag::Shield,
    ];
}
