// Mirrors upstream core/src/mindustry/audio. Implemented incrementally from D:\MDT\mindustry-upstream-v157.4.

pub mod sound_control;
pub mod sound_loop;
pub mod sound_priority;

/// Java `Sounds` ids are generated by `AssetsProcess.processSounds(...)` from
/// `core/assets/sounds`, sorted by file name. Keep this narrow table in sync with
/// the upstream baseline when wiring sound packets/local playback.
pub fn standard_sound_id(name: &str) -> Option<i16> {
    match name {
        "unitCreate" => Some(190),
        "unitCreateBig" => Some(191),
        _ => None,
    }
}

pub use sound_control::{
    FilterFadePlan, LoopSoundAction, LoopSoundPlan, MusicAction, MusicPlayInput, MusicPlaybackPlan,
    MusicRegisterPlan, SoundBusPlan, SoundControl, SoundDarkChance, SoundData,
};
pub use sound_loop::{SoundLoop, SoundLoopBackend};
pub use sound_priority::{
    SoundAssetLength, SoundFloatSetting, SoundGroupSetting, SoundIntSetting, SoundPriority,
    SoundPriorityPlan,
};

#[cfg(test)]
mod tests {
    use super::standard_sound_id;

    #[test]
    fn standard_sound_ids_follow_upstream_assets_process_order() {
        assert_eq!(standard_sound_id("unitCreate"), Some(190));
        assert_eq!(standard_sound_id("unitCreateBig"), Some(191));
        assert_eq!(standard_sound_id("missing"), None);
    }
}
